### ISSUE TITLE
Create GRT data endpoints

### ISSUE THREAD

**Issue by KartikTalwar** [uwaterloo/Parsers#2]
Assuming data files are given, the repo will contain the functions that parse GRT data and create useful endpoints to retrieve it. This is a continuation of uwaterloo/opendata#58.

@axyjo can you first draft (with sample responses) what the endpoints will be called and return before implementing it

**Comment by axyjo** [comment]
Sounds good -- I'll work on it tomorrow.

**Comment by KartikTalwar** [comment]
updates?

**Comment by axyjo** [comment]
Didn't get a chance yet. South of the border for thanksgiving.

**Comment by axyjo** [comment]
`/v2/grt`

``` json
{
    "agency_name":"Grand River Transit",
    "agency_url":"http://www.grt.ca",
    "agency_timezone":"America/New_York",
    "agency_lang":"",
    "agency_phone":"519-585-7555",
    "_links": {
        "self": {
            "href": "/v2/grt"
        },
        "stops": {
            "href": "/v2/grt/stops"
        },
        "routes": {
            "href": "/v2/grt/routes"
        }
    }
}
```

`/v2/grt/stops`

``` json
[
    {
        "stop_id":1000,
        "stop_code":"",
        "stop_name":"Frederick / King",
        "stop_desc":"",
        "stop_lat":  43.449665,
        "stop_lon": -80.487205,
        "zone_id":"",
        "stop_url":"",
        "location_type":"0",
        "parent_station":""
    },
    {
        "stop_id":1001,
        "stop_code":"",
        "stop_name":"Frederick / Irvin",
        "stop_desc":"",
        "stop_lat":  43.452326,
        "stop_lon": -80.484192,
        "zone_id":"",
        "stop_url":"",
        "location_type":"0",
        "parent_station":""
    },
    ...
]
```

`/v2/grt/stops/1000`

``` json
{
    "stop_id":1000,
    "stop_code":"",
    "stop_name":"Frederick / King",
    "stop_desc":"",
    "stop_lat":  43.449665,
    "stop_lon": -80.487205,
    "zone_id":"",
    "stop_url":"",
    "location_type":"0",
    "parent_station":""
}
```

`/v2/grt/routes`

``` json
[
    {
        "route_id":1,
        "route_short_name":1,
        "route_long_name":"Stanley Park",
        "route_desc":"",
        "route_type":3,
        "route_url":""
    },
    {
        "route_id":2,
        "route_short_name":2,
        "route_long_name":"Forest Hill",
        "route_desc":"",
        "route_type":3,
        "route_url":""
    },
    ...
]
```

`/v2/grt/routes/1`

``` json
{
    "route_id":1,
    "route_short_name":1,
    "route_long_name":"Stanley Park",
    "route_desc":"",
    "route_type":3,
    "route_url":"",
    "_links": {
        "self": {
            "href": "/v2/grt/routes/1"
        },
        "trips": {
            "href": "/v2/grt/routes/1/trips"
        }
    }
}
```

`/v2/grt/routes/19/trips`

``` json
[
    {
        "route_id":19,
        "service_id":"13FALL-All-Weekday-05",
        "trip_id":754567,
        "trip_headsign":"19 Victoria South to Highland Hills",
        "direction_id":"0",
        "block_id":121355,
        "shape_id":190004
    },
    {
        "route_id":19,
        "service_id":"13FALL-All-Weekday-05",
        "trip_id":754568,
        "trip_headsign":"19 Victoria South to Highland Hills",
        "direction_id":"0",
        "block_id":121384,
        "shape_id":190004
    },
    ...
]
```

`/v2/grt/trips/754567/stops`

``` json
[
    {
        "trip_id":754567,
        "arrival_time":"15:30:00",
        "departure_time":"15:30:00",
        "stop_id":2556,
        "stop_sequence":1,
        "pickup_type":"0",
        "drop_off_type":"0"
    },
    {
        "trip_id":754567,
        "arrival_time":"15:31:00",
        "departure_time":"15:31:00",
        "stop_id":1891,
        "stop_sequence":2,
        "pickup_type":"0",
        "drop_off_type":"0"
    },
    ...
]
```

**Comment by KartikTalwar** [comment]
Look good!
- Do you know what most of the fields returned in  `/v2/grt/routes/19/trips` mean?
- I think its missing an endpoint id like to see `/v2/grt/stops/1001/times`
- Curious about why you included `_links` for parent methods. I've seen it in other apis, but..
- Looking at the grt zip file, should we also incorporate fares and calendars?

**Comment by axyjo** [comment]
> Do you know what most of the fields returned in /v2/grt/routes/19/trips mean?

They're for displaying bounding-boxes when the route is drawn out on a map.

> I think its missing an endpoint id like to see /v2/grt/stops/1001/times

Yep! I was thinking about what the best way to do that would be (embedded objects, or a different endpoint for each trip). The above is still a work in progress.

> Curious about why you included _links for parent methods. I've seen it in other apis, but..

Allows for better self-discovery/self-documentation of the API, so that consumers can see exactly where to retrieve information related to the current document.

> Looking at the grt zip file, should we also incorporate fares and calendars?

We'll definitely need to incorporate calendars. The GTFS fares file doesn't provide a whole lot (besides the cost of a cash fare).

**Comment by KartikTalwar** [comment]
> Allows for better self-discovery/self-documentation of the API, so that consumers can see exactly where to retrieve information related to the current document.

I see that and seems helpful but I had 2 concerns: its structure is complex (2 levels) vs [github](https://api.github.com) and the consistency breaks when compared to the rest of the api

> We'll definitely need to incorporate calendars. The GTFS fares file doesn't provide a whole lot (besides the cost of a cash fare).

Agree its not much data, but mentioned it because you had `/v2/grt` as and endpoint, which is also 5 keys

**Comment by axyjo** [comment]
Yeah, I see what you mean about the complexity. The reason why I did it initially is because it's a [spec](http://stateless.co/hal_specification.html) with all kinds of libraries built around it. Applications not supporting it can simply ignore the `_links` key. I'm okay with either way though.

Re: fares -- fair enough.

**Comment by KartikTalwar** [comment]
Yeah, I think we can talk about the meta information later but feel free to implement it for now. To put it up on the api, I just need to map a function to an endpoint so if you were to create a `GRT` class and have these functions parse the text/csv files, we'd be good to go. I think all the files can be opened directly except the schedules so I'll put that in a db (or we can work of a small chunk of that data and then change the source). I can create the class file here if you want.

**Comment by nathanv** [comment]
Sweet work folks! Do you think we can get this endpoint announced in time for [SE Hackday 11](https://www.facebook.com/events/244002865762149/)? Also.. I spotted this great open source initiative called [onebusaway](http://developer.onebusaway.org/modules/onebusaway-application-modules/current/api/where/index.html) which seems to be a very significant and well maintained effort along the same lines.

**Comment by KartikTalwar** [comment]
I really like the way onesubway is organizing the data! Would love to adopt things from them

**Comment by axyjo** [comment]
I'll definitely take a look at onebusaway when creating the parser.

**Comment by KartikTalwar** [comment]
ETA on the parser? Already been a month

**Comment by axyjo** [comment]
Totally forgot about this -- might do something with this for EngHack tomorrow.

In the mean time:

http://realtimemap.grt.ca/Map/GetVehicles
http://realtimemap.grt.ca/Map/GetStops?routeId=200
http://realtimemap.grt.ca/Map/GetVehiclesByRouteId?routeId=200

Many more like these as well. These update real-time :grinning:
